### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [cyberboysumanjay/JioSaavnAPI#10]
https://jiosaavn.ga/api/?query=https://www.jiosaavn.com/song/devil-eyes/FxBcYiBJQ

{
  "error": "list index out of range", 
  "status": true
}

Why this error?

**Comment by cyberboysumanjay** [comment]
Because the song link is not valid.

Please note that the song you're looking for is available on this link https://www.jiosaavn.com/song/devil-eyes/FxBcYiBJQHg
not the one which you specified :laughing: 

Sending a GET Request at the correct URL works fine 
https://jiosaavn.ga/api/?query=https://www.jiosaavn.com/song/devil-eyes/FxBcYiBJQHg

**Comment by ParveenBhadooOfficial** [comment]
😆

**Comment by ParveenBhadooOfficial** [comment]
Thanks, Had to change the code to use the new update but it works good now. Also my website supports downloading with Original Name now.

**Comment by cyberboysumanjay** [comment]
Yeah the new update uses new schema so old codes will stop working. Even musify is dead :sweat_smile: I need to push a fix for that too
